### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by SorinaAvram** [salt-die/Chisel#1]
I have installed everything mentioned in requirements. txt; 
I still get  the error. 
From this tutorial : https://napuzba.com/a/import-error-relative-no-parent/p3 I've tried creating a new folder called new_chisel that contains main.py and then copied the rest of the folder. Did not work. 

Any idea on how to make the game work?

**Comment by salt-die** [comment]
Just to double check, from the command line one should do the following:

`git clone https://github.com/salt-die/Chisel`
`cd Chisel`
`python -m pip install -r requirements.txt`
`garden install navigationdrawer`
`python -m chisel`

and it should start.   Did any of these steps fail?

**Comment by SorinaAvram** [comment]
Hi, 

Using the command line, it worked! 
Initially i cloned it directly in git desktop assistant and installed all the requirements separately. 

Thank you SO much!
